name: Container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
        - name: Docker Commands
          run: |
           docker ps
           docker volume ls
        - name: Post a user
          run: "curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json' -D '{\"username\": \"user1\",\"address\": \"addr1\"}'"
        - name: Get Users
          run: "curl http://localhost:3001/api/users"